apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: example-ui
  template:
    metadata:
      labels:
        app: example-ui
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
          name: example-ui
          ports:
            - containerPort: 80